### ISSUE TITLE
changeValue is not working as expected

### ISSUE THREAD

**Issue by naivefun** [darekf77/lodash-walk-object#1]
https://github.com/darekf77/lodash-walk-object/blob/9a7f9ae4f47caf965fa61e74ff92eda1767339c2/src/index.ts#L32

I believe the correct code should be:
`_.set(json, lodashPath, newValue)`

Right now I'm getting wrong result like this:

```js
walk.Object(data, (value, lodashPath, changeValue) => {
  if (lodashPath.endsWith('$ref')) {
    changeValue('123456');
  }
});
```

<img width="290" alt="screen shot 2019-01-28 at 6 13 15 pm" src="https://user-images.githubusercontent.com/10683378/51829414-70d23880-2328-11e9-8d9d-668a76a2448f.png">

**Comment by darekf77** [comment]
It is working here: https://stackblitz.com/edit/typescript-uxnlq3

**Comment by naivefun** [comment]
@darekf77  not in my browser

<img width="785" alt="screen shot 2019-01-31 at 12 15 36 pm" src="https://user-images.githubusercontent.com/10683378/52030262-ff75ce00-2551-11e9-97ac-202112bfa1b5.png">

**Comment by darekf77** [comment]
ok done in version 0.0.9

**Comment by darekf77** [comment]
@naivefun  try again https://stackblitz.com/edit/typescript-uxnlq3.
